name: cart ci
on: push
jobs:
    Build:
      runs-on: ubuntu-latest
      steps: 
        - run: echo build
        - name: check out code
          uses: actions/checkout@v4
    Test:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v4
        - run: echo Test
    Deploy:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v4
        - run: echo deploy


